<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_standard_userlocked_out_userproblem_use_5284cf</name>
   <tag></tag>
   <elementGuidId>8e558973-372b-47d2-a228-735c94d7c1da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.bot_column</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>70eabd8c-dee1-4487-86d8-25d2c2398adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bot_column</value>
      <webElementGuid>3c420dc3-59b5-4617-8fbc-357c0d57005c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>img/Login_Bot_graphic.png</value>
      <webElementGuid>6a00f8f1-3e83-4cb5-bd76-54c4d4aac357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;main-body&quot;]/div[@class=&quot;login_wrapper&quot;]/div[@class=&quot;login_wrapper-inner&quot;]/img[@class=&quot;bot_column&quot;]</value>
      <webElementGuid>9be11b77-e220-4def-b5ee-6b7c6dc07b50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>d5719ba4-6f84-4ff0-9367-054cfe3df30f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'img/Login_Bot_graphic.png']</value>
      <webElementGuid>73a3b193-b267-4ce8-9223-0b8e9cec0e00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
