<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>c88fa912-34e3-4940-947e-16e676c49fc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#QuickLinks > a > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='QuickLinks']/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#QuickLinks >> internal:role=link >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>58e41878-6adc-41ab-8135-58293e0581ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/sm_fish.gif</value>
      <webElementGuid>d6af7fa2-78e4-4877-bc8d-191f697a45dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QuickLinks&quot;)/a[1]/img[1]</value>
      <webElementGuid>2307d5ce-7b88-41fe-8b78-4537c2518a49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='QuickLinks']/a/img</value>
      <webElementGuid>eaf8f432-0593-439e-b662-f680725cd8d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/img</value>
      <webElementGuid>5492c974-1b2d-4d7e-ba3d-eb51d4fcc0aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../images/sm_fish.gif']</value>
      <webElementGuid>a6e1560a-3b59-4438-beae-dee997b20696</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
